<table border="1">
    <tr>
        <td>
           Recebidas
        </td>
        <td>
           Enviadas
        </td>
    </tr>
    <tr>
        <?php
        foreach(array('recebidas', 'enviadas') as $tipo) {
            ?><td style="vertical-align: top">
            <table border="1">
                <tr>
                    <td>Data envio:</td>
                    <td>Status:</td>
                    <td>Foto:</td>
                    <td>Usuário:</td>
                </tr><?php
                foreach($this->mensagens[$tipo] as $mensagem) {
                    ?>
                    <tr>
                        <td><?php echo $mensagem['data_envio'];?></td>
                        <td>
                            <img src="/img/Gnome-mail-<?php
                                echo $mensagem['status'] ? 'read' : 'unread';
                            ?>.svg" />
                        </td>
                        <td>
                            <img src="<?php echo $mensagem['img_src']; ?>" />
                        </td>
                        <td>
                            <a href="/index/perfil/?id=<?php echo $mensagem['usuario_id'];?>"><?php
                                echo iconv("UTF-8", "ISO-8859-1", $mensagem['apelido']);
                            ?></a>
                        </td>
                    </tr><?php
                }
            ?></table>
            </td><?php
        }
        ?>
    </tr><?php
    if($this->proxima) {
        ?><tr>
            <td colspan="2" style="text-align: center">
                <a href="/index/inbox?pagina=<?php
                echo $this->proxima;
                ?>"><?php echo $this->proxima; ?></a>
            </td>
        </tr><?php
    }
    ?>
</table>