<?php
if(!isset($this->user)) {
    ?>Perfil sendo processado, a página irá atualizar dentro de 8 segundos
    caso a página não atualize automaticamente, clique no link abaixo:<br /><br /><?php
}
?><a href="/index/perfil/?id=<?php echo $this->user['id'];?>&update=1">
    atualizar
</a><?php
if(!isset($this->user)) {
    return;
}
?>
<table border="1" style="width: 100%">
<tr>
    <td>
        <a href="<?php echo $this->user['url_perfil'];?>" target="blank"><?php
        if(isset($this->user['img_url'])) {
            foreach($this->user['img_url'] as $img) {
                ?><img src="<?php echo $img['url'];?>" alt="<?php echo $img['alt'];?>" /><?php
            }
        } else {
            echo $this->user['apelido'];
        }
        ?></a>
    </td>
    <td style="width: 300px">
        <table border="1">
            <tr>
                <td>Apelido</td><td><?php echo $this->user['apelido'];?></td>
            </tr>
            <tr>
                <td>Estado Civil</td><td><?php echo $this->user['estado_civil'];?></td>
            </tr>
            <tr>
                <td>Idade</td><td><?php echo $this->user['idade'];?></td>
            </tr>
            <tr>
                <td>Altura</td><td><?php echo $this->user['altura'];?></td>
            </tr>
            <tr>
                <td>Peso</td><td><?php echo $this->user['peso'];?></td>
            </tr>
            <tr>
                <td>Quer ter filhos</td><td><?php echo $this->user['quer_ter_filhos'];?></td>
            </tr>
            <tr>
                <td>Denominacao</td><td><?php echo $this->user['denominacao'];?></td>
            </tr>
            <tr>
                <td>Profissao</td><td><?php echo $this->user['profissao'];?></td>
            </tr>
            <tr>
                <td>Formacao</td><td><?php echo $this->user['formacao'];?></td>
            </tr>
            <tr>
                <td>Updated</td><td><?php echo $this->user['updated'];?></td>
            </tr>
            <tr>
                <td>Ultimo acesso</td><td><?php echo $this->user['ultimo_acesso'];?></td>
            </tr>
            <tr>
                <td>Status</td>
                <td>
                    <img src="/img/icon_<?php echo strtolower($this->user['status']); ?>.gif">
                    <?php echo $this->user['status'];?>
                </td>
            </tr>
        </table>
    </td>
</tr>
</table>
<table border="1"><?php
foreach($this->user as $key => $value) {
    if(in_array($key, array('img_url'))) continue;
    if(in_array($key, array('denominacao_id'))) continue;
    ?><tr><td><?php echo $key;?></td><td><?php echo $value;?></td></tr><?php
}?>
</table><?php
if($this->mensagens) {
    ?>
    <table border="1">
        <tr>
            <td>Data envio:</td>
            <td>Status:</td>
            <td>Mensagem:</td>
        </tr><?php
        foreach($this->mensagens as $mensagem) {
            ?>
            <tr>
                <td><?php echo $mensagem['data_envio'];?></td>
                <td>
                    <img src="/img/Gnome-mail-<?php
                        echo $mensagem['status'] ? 'read' : 'unread';
                    ?>.svg" />
                </td>
                <td><?php echo nl2br(iconv("ISO-8859-1", "UTF-8", str_replace("\n", "\n\n", $mensagem['mensagem'])) );?></td>
            </tr><?php
        }
    ?></table><?php
}
?>
<form action="/index/send-message" method="POST">
    <input type="hidden" name="id" value="<?php echo $this->user['id'];?>">
    <textarea name="mensagem" rows="15" cols="80"></textarea>
    <input type="submit">
</form>